### ISSUE TITLE
automatic marshallers from nested case classes

### ISSUE THREAD

**Issue by fommil** [ceedubs/ficus#14]
(brain dumping)

After having used shapeless' `LabelledGeneric` quite a lot recently, I'm pretty sure it should be possible to create a nested bunch of case classes and have it automatically populated with the fqns as defined by the field names from a config file (via your typed providers, which can be pulled in implicitly).

This is something I've wanted for a while and unfortunately I've been stuck in a project for the last 18 months which has written its own property layer (my opinion withheld) so I never had a burning desire to implement this idea.

If I ever get round to it, I'll certainly send you a PR.

**Comment by fommil** [comment]
actually, you don't support nesting already, do you?

**Comment by ceedubs** [comment]
@fommil firstly, I apologize for the long delay. I just now noticed this issue.

Nested case classes should work out of the box. Though I think recursive types will probably blow my macro up.

I wrote this before I was very familiar with Shapeless, and yes I agree that `LabelledGeneric` would have probably been a more elegant approach. However, one useful thing that the macros currently provide that couldn't be done with `LabelledGeneric` is handling of default values.

Thirdly, I'm seriously neglecting Ficus these days. We have an internal configuration library, so I don't us this anymore. I'm familiar with your work on Shapeless, and I would be happy to add you as a (hopefully more diligent than I) maintainer if you are interested.

**Comment by ceedubs** [comment]
Update:

Shapeless now has support for default values. If I were to write ficus from scratch right now, it would probably just be a micro library that provides [Knobs](http://oncue.github.io/knobs/) [`Configured`](https://github.com/oncue/knobs/blob/master/core/src/main/scala/knobs/Configured.scala) instances via Shapeless derivation. In fact, I suspect that at some point I will write such a library, and if I do, I'll provide a link in the Ficus readme suggesting the alternative.

**Comment by lewismj** [comment]
I came across this and thanks to some (a lot of help) I managed to write something that I think fits the bill here: https://github.com/lewismj/kea/blob/master/core/src/main/scala/kea/generic.scala
In my lib, I want to return 'Validated'. So, it is a bit different to Ficcus. But, I could probably make a change to this lib, if anyone wanted it (or trusted me to make the change).
