### ISSUE TITLE
Add ValueReader instance for scalaz.Maybe

### ISSUE THREAD

**Issue by julien-truffaut** [ceedubs/ficus#9]

**Comment by ceedubs** [comment]
@julien-truffaut I don't plan on adding a scalaz dependency to Ficus, so I'm going to close this issue out. I would certainly encourage anyone who is interested to create a ficus-scalaz project that provides `ValueReader` instances for scalaz data structures (such as `Maybe`), a `Functor[ValueReader]` instance, etc.
